// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nqueen.proto
#ifndef GRPC_nqueen_2eproto__INCLUDED
#define GRPC_nqueen_2eproto__INCLUDED

#include "nqueen.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace nqueen {

class NQueenSolver final {
 public:
  static constexpr char const* service_full_name() {
    return "nqueen.NQueenSolver";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::nqueen::TaskResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nqueen::TaskResult>> AsyncSolve(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nqueen::TaskResult>>(AsyncSolveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nqueen::TaskResult>> PrepareAsyncSolve(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nqueen::TaskResult>>(PrepareAsyncSolveRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nqueen::TaskResult>* AsyncSolveRaw(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nqueen::TaskResult>* PrepareAsyncSolveRaw(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::nqueen::TaskResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nqueen::TaskResult>> AsyncSolve(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nqueen::TaskResult>>(AsyncSolveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nqueen::TaskResult>> PrepareAsyncSolve(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nqueen::TaskResult>>(PrepareAsyncSolveRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Solve(::grpc::ClientContext* context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nqueen::TaskResult>* AsyncSolveRaw(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nqueen::TaskResult>* PrepareAsyncSolveRaw(::grpc::ClientContext* context, const ::nqueen::TaskRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Solve_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Solve(::grpc::ServerContext* context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Solve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Solve() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Solve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Solve(::grpc::ServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSolve(::grpc::ServerContext* context, ::nqueen::TaskRequest* request, ::grpc::ServerAsyncResponseWriter< ::nqueen::TaskResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Solve<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Solve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Solve() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nqueen::TaskRequest, ::nqueen::TaskResult>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::nqueen::TaskRequest* request, ::nqueen::TaskResult* response) { return this->Solve(context, request, response); }));}
    void SetMessageAllocatorFor_Solve(
        ::grpc::experimental::MessageAllocator< ::nqueen::TaskRequest, ::nqueen::TaskResult>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nqueen::TaskRequest, ::nqueen::TaskResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Solve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Solve(::grpc::ServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Solve(
      ::grpc::CallbackServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Solve(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Solve<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Solve<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Solve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Solve() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Solve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Solve(::grpc::ServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Solve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Solve() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Solve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Solve(::grpc::ServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSolve(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Solve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Solve() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Solve(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Solve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Solve(::grpc::ServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Solve(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Solve(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Solve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Solve() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nqueen::TaskRequest, ::nqueen::TaskResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nqueen::TaskRequest, ::nqueen::TaskResult>* streamer) {
                       return this->StreamedSolve(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Solve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Solve(::grpc::ServerContext* /*context*/, const ::nqueen::TaskRequest* /*request*/, ::nqueen::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSolve(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nqueen::TaskRequest,::nqueen::TaskResult>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Solve<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Solve<Service > StreamedService;
};

}  // namespace nqueen


#endif  // GRPC_nqueen_2eproto__INCLUDED
